on join:
	set {detectCount.%player%} to 0
	set {baritoneFlags.%player%} to 0

	set {yaw.%player%} to yaw of player
	set {lastYaw.%player%} to yaw of player

	{lastY.%player%} = 0
	set {detectCount.%player%} to 0
	
on player move:
	set {_diff.%player%} to abs(yaw of player - {lastYaw.%player%})

	set {_y.%player%} to y-coordinate of player
	set {_y.%player%} to round({_y.%player%})

	set {mod.%player%} to mod(yaw of player, 90) 

	if {mod.%player%} <= 1:
		set {perfectStraightYaw.%player%} to true
	else:
		set {perfectStraightYaw.%player%} to false
	if {mod.%player%} > 89.5:
		if {mod.%player%} < 90:
			set {perfectStraightYaw.%player%} to true
	else:
		set {perfectStraightYaw.%player%} to false
	
	set {lastY.%player%} to round({lastY.%player%})
	if round({_y.%player%}) is round({lastY.%player%}):
		set {_x.%player%} to x-coordinate of player
		set {_decimalX.%player%} to {_x.%player%} - floor({_x.%player%})
		
		set {_z.%player%} to z-coordinate of player
		set {_decimalZ.%player%} to {_z.%player%} - floor({_z.%player%})
		
		add 1 to {loop.%player%}
		
		set {current.%player%} to location of player
		
		if block under player is not air:
			if block above player is not water:
				if {_diff.%player%} < 0.1:
					if {perfectStraightYaw.%player%} is true:
						if {_decimalX.%player%} >= 0.49:
							if {_decimalX.%player%} <= 0.51:
								add 1 to {detectCount.%player%}
								if {detectCount.%player%} >= 7:
									add 1 to {baritoneFlags.%player%}
									send "&8[&6&lRuinborn&8] &7Gracz %player% zostal oznaczony podejrzeniem o nielegalne oprogramowanie Baritone! %{baritoneFlags.%player%}%&8/&e10" to console
								
						if {_decimalZ.%player%} >= 0.49:
							if {_decimalZ.%player%} <= 0.51:
								add 1 to {detectCount.%player%}
								if {detectCount.%player%} >= 7:
									add 1 to {baritoneFlags.%player%}
									send "&8[&6&lRuinborn&8] &7Gracz %player% zostal oznaczony podejrzeniem o nielegalne oprogramowanie Baritone! %{baritoneFlags.%player%}%&8/&e10" to console

						if {baritoneFlags.%player%} >= 5:
							set {warning.%player%} to 1
							
						if {loop.%player%} >= 400:
							set {detectCount.%player%} to 0
							set {baritoneDetection.%player%} to 0
							set {loop.%player%} to 0
							
						if {baritoneFlags.%player%} >= 10:
						
							set {baritoneDetection.%player%} to 0
							set {baritonebaritoneFlags.%player%} to 0
							set {detectCount.%player%} to 0
							kick player due to "&6&lRuinborn&8%nl%%nl%&8-------------------- %nl%%nl%&e&lWystapil niezidentyfikowany problem. Najmocniej przepraszamy. %nl%%nl%&r&7Mozesz ponownie polaczyc sie z serwerem. %nl%%nl%&8--------------------"
						
						if {warning.%player%} = 1:
							if {alreadyWarned.%player%} != 1:
								if block under player is not air:
									if block above player is not water:
										set {alreadyWarned.%player%} to 1
										wait 5 seconds
										set {warning.%player%} to 0
										set {alreadyWarned.%player%} to 0

	set {lastYaw.%player%} to yaw of player
	set {lastY.%player%} to {_y.%player%}
	
